# AEM Sites Optimizer Configuration
# Please update the site_url below with your actual Site URL
site_url: "https://publish-p166568-e1781270.adobeaemcloud.com/"

# Example:
# site_url: "https://your-site.com"
